---
title: "Reporte Clínico de Variantes"
author: "Di Genoma Lab"
date: "`r Sys.Date()`"
output: rmarkdown::github_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE)
#library(tidyverse)
library(kableExtra)
library(maftools)
```

## Metricas de Calidad

```{r fun_PlotQC, echo=FALSE, warning=FALSE}

plotQC <- function(data,title,color) {
  
plot <- ggplot(data, aes(x=variable, y = value)) +
  geom_violin(trim = FALSE, fill =color, color =color, alpha = 0.1) + 
  geom_jitter(width = 0.2, size = 1.5, color =color) + # Puntos transparentes
  stat_summary(
    fun = median, 
    geom = "crossbar", 
    width = 2, 
    linetype = "dashed", 
    color = "black", 
    alpha = 0.9,
    size = 0.2 
  ) + 
  coord_flip() + 
  theme_minimal(base_size = 10) + 
  theme(
    panel.grid.major = element_line(color = "gray90"),
    plot.title = element_text(hjust = 0.5),
    axis.line.y = element_blank(),
    axis.text.y = element_blank(),
    axis.ticks.y = element_blank(),
    axis.line = element_blank(),
    axis.ticks = element_blank()
  ) +
  labs(x ="", y ="", title = title) +
  theme(
    plot.title = element_text(face = "bold")
  )
return(plot)
}
```

```{r, echo=FALSE, include=FALSE}
library(reshape2)
library(cowplot)
library(dplyr)
library(ggplot2)

general_qc<-read.csv("/mnt/beegfs/home/efeliu/work2024/080524_nextflow_BRCA/HRR_RunBRCA/multiqc_data/multiqc_general_stats.txt", sep = '\t')
melt_data<-melt(general_qc)

## Plot N1
total_reads<-melt_data %>% filter(variable=="FastQC_mqc_generalstats_fastqc_total_sequences" & !is.na(value))
#total_reads$value<-as.numeric(total_reads$value/1000000)
plot.total_reads<-plotQC(total_reads,"Total Reads (M)","#1B9E77")
## Plot N2
pct_aligned<-melt_data %>% filter(variable=="QualiMap_mqc_generalstats_qualimap_percentage_aligned" & !is.na(value))
plot.pct_aligned<-plotQC(pct_aligned,"Aligned Reads (%)","#E7298A")
## Plot N3
percentage_50X<-melt_data %>% filter(variable=="QualiMap_mqc_generalstats_qualimap_mqc_50_x_pc" & !is.na(value))
plot.percentage_50X<-plotQC(percentage_50X,"Reads with ≥50X Coverage (%)","#E6AB02")
## plot N4
mean_coverage<-melt_data %>% filter(variable=="QualiMap_mqc_generalstats_qualimap_mean_coverage" & !is.na(value))
plot.mean_coverage<-plotQC(mean_coverage,"Mean Coverage","#7570B3")
## plot N5
median_insert_size<-melt_data %>% filter(variable=="QualiMap_mqc_generalstats_qualimap_median_insert_size" & !is.na(value))
plot.median_insert_size<-plotQC(median_insert_size,"Median Insert Size (bp)","#66A61E")
## plot N6
gc<-melt_data %>% filter(variable=="QualiMap_mqc_generalstats_qualimap_avg_gc" & !is.na(value))
plot.gc<-plotQC(gc,"GC Content (%)","#D95F02")

combined_plot1 <- plot_grid(plot.total_reads, plot.pct_aligned,
                           plot.mean_coverage,plot.percentage_50X,
                           plot.median_insert_size,plot.gc, ncol = 2,nrow = 3,
                         labels = c("A", "B","C","D","E","F"))
```

```{r, echo=FALSE}
combined_plot1
```
## Resumen

```{r, echo=FALSE, include=FALSE}
#Rscript -e "rmarkdown::render('Variants_Report.Rmd')"
filenames.s <- Sys.glob("/mnt/beegfs/home/efeliu/work2024/080524_nextflow_BRCA/HRR_RunBRCA/annovar/*SS*hg38_multianno.txt")
annovar_mafs.s = lapply(filenames.s, annovarToMaf,refBuild = "hg38")
annovar.s = data.table::rbindlist(l = annovar_mafs.s, fill = TRUE) 

vcNames <-c("Frame_Shift_Del","Frame_Shift_Ins","Missense_Mutation","Nonsense_Mutation")

summary = read.maf(maf = annovar.s, vc_nonSyn = vcNames)
```

```{r, echo=FALSE}

plotmafSummary(maf=summary, rmOutlier = TRUE, addStat = 'median', dashboard = TRUE, titvRaw = FALSE, showBarcodes = FALSE, textSize = 0.6)
```
## Reporte por Paciente
